# SPDX-FileCopyrightText: 2025 Håkon Løvdal <kode@denkule.no>
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: |
            (?x)^(
                \.vscode/.*\.json$|
                tsconfig.*\.json$
            )$
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                supabase/.branches/_current_branch$|
                supabase/.temp/cli-latest$
            )$
-   repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    - id: check-json5
      files: |
            (?x)^(
                \.vscode/.*\.json$|
                tsconfig.*\.json$
            )$
