# SPDX-FileCopyrightText: 2025 Håkon Løvdal <kode@denkule.no>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow will deploy to www.1maiprogram.no.

name: Deploy

on:
  push:
    branches: [ "main", "deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Copy dist files to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        source: dist/1maiprogram/browser
        target: ${{ secrets.DEPLOY_WWW_PARENT_DIR }}/upload
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        script: |
          set -euo pipefail
          cd ${{ secrets.DEPLOY_WWW_PARENT_DIR }}
          set -xv
          mkdir test.www.new
          mv upload/dist/1maiprogram/browser/* upload/dist/1maiprogram/browser/.??* test.www.new/.
          cp -ai test.www/.git* test.www.new/.
          cd test.www.new
          git add .
          git commit -m "$(date "+%Y-%m-%d_%H:%M")"
          cd ..
          mv test.www test.www."$(date "+%Y-%m-%d_%H:%M")"
          mv test.www.new test.www
          ls -ld test.www*
