# SPDX-FileCopyrightText: 2025 Håkon Løvdal <kode@denkule.no>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "ci_test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Install pre-commit, reuse
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.3
    - run: pip install pre-commit
    - run: pre-commit --version
    - run: pip install reuse
    - run: reuse --version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: ./bin/run-test-test.sh
    - run: ./bin/run-test-pre-commit.sh
    - run: ./bin/run-test-reuse-lint.sh
    #- run: ./bin/run-test-shellcheck.sh
